# This script is for generating a markdown summary of the data generated by learnset_data.py

import os

# Learnset data module
from learnset_data import get_learnset_data

# Output data file (markdown)
LEARNSET_DATA_OUT_MD = "learnset_data.md"

def get_learnset_markdown(data): 

    # Output document contents
    lines = []

    # Dereference species list
    species_list = data.keys()

    # Loop over the species
    for species in species_list:

        # Dereference species data
        species_data = data[species]

        # Add species name as subtitle
        lines.append(f"## {species_data['name']}")

        # Species has teachable moves
        if 'teachable' in species_data and len(species_data['teachable']) > 0:
            lines.append("### Teachable Moves")
            lines.append(f"{", ".join(species_data['teachable'])}")
            lines.append("")
        
        # Species has egg moves
        if 'egg' in species_data and len(species_data['egg']) > 0: 
            lines.append("### Egg Moves")
            lines.append(f"{", ".join(species_data['egg'])}")
            lines.append("")

        # Species has level-up moves
        if 'levelup' in species_data and len(species_data['levelup']) > 0:
            lines.append("### Level Up Moves")
            
            # Build level-up moves list 
            # Format: move (level), ...
            levelup = []
            for move in species_data['levelup']:
                levelup.append(f"{move['name']} ({move['level']})")

            lines.append(f"{", ".join(levelup)}")
            lines.append("")

    # Return joined document
    return "\n".join(lines)

if __name__ == '__main__':

    # Build learnset data file
    learnset_data = get_learnset_data()

    markdown = get_learnset_markdown(learnset_data)

    # Get the path to the running script
    script_path = os.path.dirname(os.path.realpath(__file__))

    # Dump learnset data to file (same directory as script)
    with open(f"{script_path}/{LEARNSET_DATA_OUT_MD}", "w") as f:
        f.write(markdown)