Common_EventScript_Placeholder::
# 7 "data/scripts/simple_npcs.pory"
	lock
# 8 "data/scripts/simple_npcs.pory"
	faceplayer
# 9 "data/scripts/simple_npcs.pory"
	msgbox Common_EventScript_Placeholder_Text_0
# 10 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter::
# 18 "data/scripts/simple_npcs.pory"
	lock
# 19 "data/scripts/simple_npcs.pory"
	faceplayer
# 20 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
# 21 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
# 22 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_2
# 23 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattlePikeGreeter::
# 29 "data/scripts/simple_npcs.pory"
	lock
# 30 "data/scripts/simple_npcs.pory"
	faceplayer
# 31 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
# 32 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattlePikeGreeter_Text_0
# 33 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_2
# 34 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattleTowerGreeter::
# 40 "data/scripts/simple_npcs.pory"
	lock
# 41 "data/scripts/simple_npcs.pory"
	faceplayer
# 42 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
# 43 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleTowerGreeter_Text_0
# 44 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_2
# 45 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattlePalaceGreeter::
# 51 "data/scripts/simple_npcs.pory"
	lock
# 52 "data/scripts/simple_npcs.pory"
	faceplayer
# 53 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
# 54 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattlePalaceGreeter_Text_0
# 55 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_2
# 56 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattlePyramidGreeter::
# 62 "data/scripts/simple_npcs.pory"
	lock
# 63 "data/scripts/simple_npcs.pory"
	faceplayer
# 64 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
# 65 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattlePyramidGreeter_Text_0
# 66 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_2
# 67 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter::
# 73 "data/scripts/simple_npcs.pory"
	lock
# 74 "data/scripts/simple_npcs.pory"
	faceplayer
# 75 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
# 76 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_0
# 77 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_1
# 78 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_ClosedAreaGreeter::
# 84 "data/scripts/simple_npcs.pory"
	lock
# 85 "data/scripts/simple_npcs.pory"
	faceplayer
# 86 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
# 87 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_ClosedAreaGreeter_Text_0
# 88 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_ClosedAreaGreeter_Text_1
# 89 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_ClosedAreaBlocker::
# 95 "data/scripts/simple_npcs.pory"
	lock
# 96 "data/scripts/simple_npcs.pory"
	faceplayer
# 97 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_ClosedAreaGreeter_Text_0
# 98 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_ClosedAreaGreeter_Text_1
# 99 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1::
# 105 "data/scripts/simple_npcs.pory"
	lock
# 106 "data/scripts/simple_npcs.pory"
	faceplayer
# 107 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_0
# 108 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_1
# 109 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_2
# 110 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2::
# 116 "data/scripts/simple_npcs.pory"
	lock
# 117 "data/scripts/simple_npcs.pory"
	faceplayer
# 118 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_0
# 119 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_1
# 120 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_2
# 121 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3::
# 127 "data/scripts/simple_npcs.pory"
	lock
# 128 "data/scripts/simple_npcs.pory"
	faceplayer
# 129 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_0
# 130 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_1
# 131 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1::
# 137 "data/scripts/simple_npcs.pory"
	lock
# 138 "data/scripts/simple_npcs.pory"
	faceplayer
# 139 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_0
# 140 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_1
# 141 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2::
# 147 "data/scripts/simple_npcs.pory"
	lock
# 148 "data/scripts/simple_npcs.pory"
	faceplayer
# 149 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_0
# 150 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_1
# 151 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1::
# 157 "data/scripts/simple_npcs.pory"
	lock
# 158 "data/scripts/simple_npcs.pory"
	faceplayer
# 159 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_0
# 160 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_1
# 161 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_2
# 162 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_3
# 163 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_4
# 164 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1::
# 170 "data/scripts/simple_npcs.pory"
	lock
# 171 "data/scripts/simple_npcs.pory"
	faceplayer
# 172 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_0
# 173 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_1
# 174 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_2
# 175 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_3
# 176 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_4
# 177 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1::
# 183 "data/scripts/simple_npcs.pory"
	lock
# 184 "data/scripts/simple_npcs.pory"
	faceplayer
# 185 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_0
# 186 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_1
# 187 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_2
# 188 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_3
# 189 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2::
# 195 "data/scripts/simple_npcs.pory"
	lock
# 196 "data/scripts/simple_npcs.pory"
	faceplayer
# 197 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_0
# 198 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_1
# 199 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_2
# 200 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3::
# 206 "data/scripts/simple_npcs.pory"
	lock
# 207 "data/scripts/simple_npcs.pory"
	faceplayer
# 208 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_0
# 209 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_1
# 210 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_2
# 211 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_3
# 212 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1::
# 218 "data/scripts/simple_npcs.pory"
	lock
# 219 "data/scripts/simple_npcs.pory"
	faceplayer
# 220 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_0
# 221 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_1
# 222 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_2
# 223 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2::
# 229 "data/scripts/simple_npcs.pory"
	lock
# 230 "data/scripts/simple_npcs.pory"
	faceplayer
# 231 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_0
# 232 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_1
# 233 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_2
# 234 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3::
# 240 "data/scripts/simple_npcs.pory"
	lock
# 241 "data/scripts/simple_npcs.pory"
	faceplayer
# 242 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_0
# 243 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_1
# 244 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_2
# 245 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1::
# 251 "data/scripts/simple_npcs.pory"
	lock
# 252 "data/scripts/simple_npcs.pory"
	faceplayer
# 253 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_0
# 254 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_1
# 255 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_2
# 256 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2::
# 262 "data/scripts/simple_npcs.pory"
	lock
# 263 "data/scripts/simple_npcs.pory"
	faceplayer
# 264 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_0
# 265 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_1
# 266 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_2
# 267 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1::
# 273 "data/scripts/simple_npcs.pory"
	lock
# 274 "data/scripts/simple_npcs.pory"
	faceplayer
# 275 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_0
# 276 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_1
# 277 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1::
# 283 "data/scripts/simple_npcs.pory"
	lock
# 284 "data/scripts/simple_npcs.pory"
	faceplayer
# 285 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_0
# 286 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_1
# 287 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_2
# 288 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1::
# 294 "data/scripts/simple_npcs.pory"
	lock
# 295 "data/scripts/simple_npcs.pory"
	faceplayer
# 296 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_0
# 297 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_1
# 298 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_2
# 299 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_UncommonItem_Visitor1::
# 305 "data/scripts/simple_npcs.pory"
	lock
# 306 "data/scripts/simple_npcs.pory"
	faceplayer
# 307 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_UncommonItem_Visitor1_Text_0
# 308 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_UncommonItem_Visitor1_Text_1
# 309 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_CommonItem_Visitor1::
# 315 "data/scripts/simple_npcs.pory"
	lock
# 316 "data/scripts/simple_npcs.pory"
	faceplayer
# 317 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_CommonItem_Visitor1_Text_0
# 318 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_CommonItem_Visitor1_Text_1
# 319 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1::
# 325 "data/scripts/simple_npcs.pory"
	lock
# 326 "data/scripts/simple_npcs.pory"
	faceplayer
# 327 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_0
# 328 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_1
# 329 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1::
# 335 "data/scripts/simple_npcs.pory"
	lock
# 336 "data/scripts/simple_npcs.pory"
	faceplayer
# 337 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_0
# 338 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_1
# 339 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_2
# 340 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_3
# 341 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1::
# 347 "data/scripts/simple_npcs.pory"
	lock
# 348 "data/scripts/simple_npcs.pory"
	faceplayer
# 349 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1_Text_0
# 350 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1_Text_1
# 351 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1::
# 357 "data/scripts/simple_npcs.pory"
	lock
# 358 "data/scripts/simple_npcs.pory"
	faceplayer
# 359 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_0
# 360 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_1
# 361 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_2
# 362 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor1::
# 368 "data/scripts/simple_npcs.pory"
	lock
# 369 "data/scripts/simple_npcs.pory"
	faceplayer
# 370 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor1_Text_0
# 371 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor1_Text_1
# 372 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor1_Text_2
# 373 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor2::
# 379 "data/scripts/simple_npcs.pory"
	lock
# 380 "data/scripts/simple_npcs.pory"
	faceplayer
# 381 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor2_Text_0
# 382 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor2_Text_1
# 383 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1::
# 391 "data/scripts/simple_npcs.pory"
	lock
# 392 "data/scripts/simple_npcs.pory"
	faceplayer
# 393 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_0
# 394 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_1
# 395 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_2
# 396 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2::
# 402 "data/scripts/simple_npcs.pory"
	lock
# 403 "data/scripts/simple_npcs.pory"
	faceplayer
# 404 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_0
# 405 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_1
# 406 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_2
# 407 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1::
# 415 "data/scripts/simple_npcs.pory"
	lock
# 416 "data/scripts/simple_npcs.pory"
	faceplayer
# 417 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_0
# 418 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_1
# 419 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_2
# 420 "data/scripts/simple_npcs.pory"
	release
	end


BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor2::
# 426 "data/scripts/simple_npcs.pory"
	lock
# 427 "data/scripts/simple_npcs.pory"
	faceplayer
# 428 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor2_Text_0
# 429 "data/scripts/simple_npcs.pory"
	msgbox BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor2_Text_1
# 430 "data/scripts/simple_npcs.pory"
	release
	end


Common_EventScript_Placeholder_Text_0:
# 9 "data/scripts/simple_npcs.pory"
	.string "Hello! I'm a placeholder NPC!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0:
# 20 "data/scripts/simple_npcs.pory"
	.string "Welcome to the Battle Frontier\n"
	.string "Underground!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1:
# 21 "data/scripts/simple_npcs.pory"
	.string "This is the closest entrance for the\n"
	.string "Battle Dome facility.$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_2:
# 22 "data/scripts/simple_npcs.pory"
	.string "Feel free to use your bike!$"

BattleFrontier_Underground_B1F_EventScript_BattlePikeGreeter_Text_0:
# 32 "data/scripts/simple_npcs.pory"
	.string "This is the closest entrance for the\n"
	.string "Battle Factory and Battle Pike\l"
	.string "facilities.$"

BattleFrontier_Underground_B1F_EventScript_BattleTowerGreeter_Text_0:
# 43 "data/scripts/simple_npcs.pory"
	.string "This is the closest entrance for the\n"
	.string "Battle Tower, Ranking Hall and BP\l"
	.string "Exchange Service facilities.$"

BattleFrontier_Underground_B1F_EventScript_BattlePalaceGreeter_Text_0:
# 54 "data/scripts/simple_npcs.pory"
	.string "This is the closest entrance for the\n"
	.string "Battle Palace, POKéMON Center and\l"
	.string "POKéMART facilities.$"

BattleFrontier_Underground_B1F_EventScript_BattlePyramidGreeter_Text_0:
# 65 "data/scripts/simple_npcs.pory"
	.string "This is the best entrance for the\n"
	.string "Battle Pyramid and Battle Arena\l"
	.string "facilities.$"

BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_0:
# 76 "data/scripts/simple_npcs.pory"
	.string "This is the entrance to the Battle\n"
	.string "Frontier Underground Pokémon Center.$"

BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_1:
# 77 "data/scripts/simple_npcs.pory"
	.string "I hope you enjoy your stay!$"

BattleFrontier_Underground_B1F_EventScript_ClosedAreaGreeter_Text_0:
# 87 "data/scripts/simple_npcs.pory"
	.string "This area is currently closed for\n"
	.string "renovations.$"

BattleFrontier_Underground_B1F_EventScript_ClosedAreaGreeter_Text_1:
# 88 "data/scripts/simple_npcs.pory"
	.string "Sorry for the inconvenience!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_0:
# 107 "data/scripts/simple_npcs.pory"
	.string "Have you been into the POKéMON Day\n"
	.string "Care yet?$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_1:
# 108 "data/scripts/simple_npcs.pory"
	.string "You can buy new training-ready\n"
	.string "POKéMON, or even breed your own!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_2:
# 109 "data/scripts/simple_npcs.pory"
	.string "It's worth checking out if you are\n"
	.string "looking to add some new POKéMON to your\l"
	.string "team!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_0:
# 118 "data/scripts/simple_npcs.pory"
	.string "Have you played the Open Level Rules at\n"
	.string "the Battle Frontier?$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_1:
# 119 "data/scripts/simple_npcs.pory"
	.string "You can use legendary POKéMON, even\n"
	.string "the most powerful ones!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_2:
# 120 "data/scripts/simple_npcs.pory"
	.string "I've heard Xerneas and Groudon are a\n"
	.string "really powerful combo!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_0:
# 129 "data/scripts/simple_npcs.pory"
	.string "I've sure been losing a lot of battles\n"
	.string "lately ...$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_1:
# 130 "data/scripts/simple_npcs.pory"
	.string "Maybe some stronger POKéMON would\n"
	.string "help?$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_0:
# 139 "data/scripts/simple_npcs.pory"
	.string "The medicine at this shop is perfect\n"
	.string "for training POKéMON.$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_1:
# 140 "data/scripts/simple_npcs.pory"
	.string "You can use a BOTTLE CAP to max out all\n"
	.string "of your POKéMON's base stats, and other\l"
	.string "items such as HP UP, Zinc and Carbos to\l"
	.string "help your POKéMON reach their full\l"
	.string "potential!$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_0:
# 149 "data/scripts/simple_npcs.pory"
	.string "My WEAVILE had a calm nature, but I\n"
	.string "used a mint to change it to a jolly\l"
	.string "nature.$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_1:
# 150 "data/scripts/simple_npcs.pory"
	.string "It's much faster and stronger now!$"

BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_0:
# 159 "data/scripts/simple_npcs.pory"
	.string "Have you entered a DYNAMAX BATTLE\n"
	.string "yet?$"

BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_1:
# 160 "data/scripts/simple_npcs.pory"
	.string "Simply turn on your DYNAMAX BAND from\n"
	.string "the KEY ITEMS menu, and you can use it\l"
	.string "in the Frontier!$"

BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_2:
# 161 "data/scripts/simple_npcs.pory"
	.string "If you don't have a DYNAMAX BAND\n"
	.string "already, you can buy one from the KEY\l"
	.string "ITEM shop at the bottom-right side of\l"
	.string "the mall.$"

BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_3:
# 162 "data/scripts/simple_npcs.pory"
	.string "Keep in mind, though - You won't be able\n"
	.string "to use Tera, Mega Evolution or Z-Moves\l"
	.string "while it is active.$"

BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_4:
# 163 "data/scripts/simple_npcs.pory"
	.string "Make sure to max out your POKéMON's\n"
	.string "dynamax level using MAX MUSHROOMS\l"
	.string "first!$"

BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_0:
# 172 "data/scripts/simple_npcs.pory"
	.string "Have you heard of Terastalisation?$"

BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_1:
# 173 "data/scripts/simple_npcs.pory"
	.string "It allows one of your POKéMON to change\n"
	.string "into a different type once per game!$"

BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_2:
# 174 "data/scripts/simple_npcs.pory"
	.string "If you don't have a Tera Orb already,\n"
	.string "you can buy one from the KEY ITEM shop\l"
	.string "at the bottom-right side of the mall.$"

BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_3:
# 175 "data/scripts/simple_npcs.pory"
	.string "The type changes depending on the\n"
	.string "POKéMON's Tera Type - Which can be\l"
	.string "changed using Tera Shards.$"

BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_4:
# 176 "data/scripts/simple_npcs.pory"
	.string "You can check the Tera Type of your\n"
	.string "POKéMON from the summary menu!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_0:
# 185 "data/scripts/simple_npcs.pory"
	.string "Psst! I'll let you in a little secret!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_1:
# 186 "data/scripts/simple_npcs.pory"
	.string "If you train your POKéMON with 252 EVs\n"
	.string "in two stats and then 4 points in\l"
	.string "another, you are missing out on two\l"
	.string "stat points!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_2:
# 187 "data/scripts/simple_npcs.pory"
	.string "If you use a spread with 4 EVs in 3\n"
	.string "stats, 244 in one, and then 252 in the\l"
	.string "other - You'll get an extra two stat\l"
	.string "points!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_3:
# 188 "data/scripts/simple_npcs.pory"
	.string "Don't share this with anyone else!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_0:
# 197 "data/scripts/simple_npcs.pory"
	.string "Berries are extremely useful for\n"
	.string "training POKéMON!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_1:
# 198 "data/scripts/simple_npcs.pory"
	.string "Some of them can be used to raise your\n"
	.string "POKéMON's base stats, and others can\l"
	.string "even be used to reduce them instead.$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_2:
# 199 "data/scripts/simple_npcs.pory"
	.string "Rely on them when making more advanced\n"
	.string "EV spreads!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_0:
# 208 "data/scripts/simple_npcs.pory"
	.string "Did you know? Sometimes, it's beneficial\n"
	.string "to have lower stats on your POKéMON!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_1:
# 209 "data/scripts/simple_npcs.pory"
	.string "On special attackers, having a low\n"
	.string "attack stat can result in opposing Foul\l"
	.string "Plays doing less damage!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_2:
# 210 "data/scripts/simple_npcs.pory"
	.string "Or on trick room POKéMON, having a low\n"
	.string "speed stat will make them faster under\l"
	.string "trick room!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_3:
# 211 "data/scripts/simple_npcs.pory"
	.string "Keep these in mind when you are\n"
	.string "training your POKéMON!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_0:
# 220 "data/scripts/simple_npcs.pory"
	.string "If your POKéMON has a major type\n"
	.string "weakness holding it back, type resist\l"
	.string "berries may be the solution!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_1:
# 221 "data/scripts/simple_npcs.pory"
	.string "These berries will halve the incoming\n"
	.string "damage of a single super-effective\l"
	.string "move of a given type.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_2:
# 222 "data/scripts/simple_npcs.pory"
	.string "This includes double weaknesses!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_0:
# 231 "data/scripts/simple_npcs.pory"
	.string "Status berries are great for saving\n"
	.string "your POKéMON in difficult situations.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_1:
# 232 "data/scripts/simple_npcs.pory"
	.string "If you get randomly frozen, paralyzed\n"
	.string "or burnt, a Lum berry will restore the\l"
	.string "status of your POKéMON once!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_2:
# 233 "data/scripts/simple_npcs.pory"
	.string "The berries for restoring a specific\n"
	.string "status are more niche, but are useful in\l"
	.string "certain situations.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_0:
# 242 "data/scripts/simple_npcs.pory"
	.string "I like to give one of my POKéMON a\n"
	.string "Sitrus Berry, so they can recover a\l"
	.string "quarter of their health each battle!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_1:
# 243 "data/scripts/simple_npcs.pory"
	.string "Other recovery berries such as Figy,\n"
	.string "Mago, etc. restore more health, but are\l"
	.string "trigged at lower health.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_2:
# 244 "data/scripts/simple_npcs.pory"
	.string "Also, make sure you use the right berry\n"
	.string "for your POKéMON's nature, or they will\l"
	.string "be confused by it!$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_0:
# 253 "data/scripts/simple_npcs.pory"
	.string "Have you been into the GAME CORNER\n"
	.string "yet?$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_1:
# 254 "data/scripts/simple_npcs.pory"
	.string "It's a fun change of pace from battling.$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_2:
# 255 "data/scripts/simple_npcs.pory"
	.string "Just don't bet more than you can afford\n"
	.string "to lose!$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_0:
# 264 "data/scripts/simple_npcs.pory"
	.string "Have you seen these vending machines\n"
	.string "around?$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_1:
# 265 "data/scripts/simple_npcs.pory"
	.string "You can use them to exchange BATTLE\n"
	.string "POINTS for money, and vice versa.$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_2:
# 266 "data/scripts/simple_npcs.pory"
	.string "Similarly, you can use the machines in\n"
	.string "the back left of the GAME CORNER to\l"
	.string "exchange coins for money!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_0:
# 275 "data/scripts/simple_npcs.pory"
	.string "You see that vending machine over\n"
	.string "there? You can use that to convert\l"
	.string "BATTLE POINTS to money!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_1:
# 276 "data/scripts/simple_npcs.pory"
	.string "You can't buy anything down here with\n"
	.string "BP, so you'll need to convert it first.$"

BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_0:
# 285 "data/scripts/simple_npcs.pory"
	.string "Gems are great! They boost the power of\n"
	.string "a POKéMON's move of the same type once\l"
	.string "by 30%, but are only used if the move\l"
	.string "connects!$"

BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_1:
# 286 "data/scripts/simple_npcs.pory"
	.string "They pair great with Unburden and\n"
	.string "Acrobatics, too.$"

BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_2:
# 287 "data/scripts/simple_npcs.pory"
	.string "Definitely think about using them!$"

BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_0:
# 296 "data/scripts/simple_npcs.pory"
	.string "Type-Boosting items are great! They\n"
	.string "boost the power of a POKéMON's move\l"
	.string "move of the same type every turn by\l"
	.string "20%!$"

BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_1:
# 297 "data/scripts/simple_npcs.pory"
	.string "They work great for POKéMON who mainly\n"
	.string "focus on a single attacking type!$"

BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_2:
# 298 "data/scripts/simple_npcs.pory"
	.string "You should consider using them!$"

BattleFrontier_Underground_B1F_EventScript_UncommonItem_Visitor1_Text_0:
# 307 "data/scripts/simple_npcs.pory"
	.string "There are lots of POKéMON that can use\n"
	.string "common items, but sometimes a less\l"
	.string "common item allows a POKéMON to really\l"
	.string "shine.$"

BattleFrontier_Underground_B1F_EventScript_UncommonItem_Visitor1_Text_1:
# 308 "data/scripts/simple_npcs.pory"
	.string "If you are struggling to pick an item,\n"
	.string "definitely take a look!$"

BattleFrontier_Underground_B1F_EventScript_CommonItem_Visitor1_Text_0:
# 317 "data/scripts/simple_npcs.pory"
	.string "Some items are so powerful, they stand\n"
	.string "in a class of their own - Almost any\l"
	.string "POKéMON can benefit from them!$"

BattleFrontier_Underground_B1F_EventScript_CommonItem_Visitor1_Text_1:
# 318 "data/scripts/simple_npcs.pory"
	.string "Whenever I'm looking for an item for a\n"
	.string "new POKéMON, this is the first place I\l"
	.string "look.$"

BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_0:
# 327 "data/scripts/simple_npcs.pory"
	.string "Z-Crystals are incredible - There is one\n"
	.string "for every type, and some POKéMON even\l"
	.string "have unique Z-Moves!$"

BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_1:
# 328 "data/scripts/simple_npcs.pory"
	.string "Be careful, though - If you use one into\n"
	.string "an immunity, it'll be wasted - and it only\l"
	.string "deals 1/4 damage through protect!$"

BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_0:
# 337 "data/scripts/simple_npcs.pory"
	.string "Mega evolution POKéMON are incredibly\n"
	.string "strong - But you can only use one per\l"
	.string "battle!$"

BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_1:
# 338 "data/scripts/simple_npcs.pory"
	.string "Some megas best used with a team built\n"
	.string "around them, and others work well to\l"
	.string "support a team.$"

BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_2:
# 339 "data/scripts/simple_npcs.pory"
	.string "If you don't have a Mega Stone already,\n"
	.string "you can buy one from the KEY ITEM shop\l"
	.string "at the bottom-right side of the mall.$"

BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_3:
# 340 "data/scripts/simple_npcs.pory"
	.string "Hmmm ... Which one do I pick this time?$"

BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1_Text_0:
# 349 "data/scripts/simple_npcs.pory"
	.string "Wow, they have the complete set of TMs\n"
	.string "and HMs here!$"

BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1_Text_1:
# 350 "data/scripts/simple_npcs.pory"
	.string "I found a few while exploring, but I'll\n"
	.string "have to buy the rest when I need them.$"

BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_0:
# 359 "data/scripts/simple_npcs.pory"
	.string "Did you know? You can swap a POKéMON's\n"
	.string "POKéBALL by simply using the ball you\l"
	.string "want on them from your bag!$"

BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_1:
# 360 "data/scripts/simple_npcs.pory"
	.string "You'll even get back the ball it was\n"
	.string "originally captured in, too.$"

BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_2:
# 361 "data/scripts/simple_npcs.pory"
	.string "Try it out for yourself!$"

BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor1_Text_0:
# 370 "data/scripts/simple_npcs.pory"
	.string "Have you had a look at the sample teams\n"
	.string "shop yet?$"

BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor1_Text_1:
# 371 "data/scripts/simple_npcs.pory"
	.string "It's a great way to get started if you\n"
	.string "aren't sure what to use!$"

BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor1_Text_2:
# 372 "data/scripts/simple_npcs.pory"
	.string "I hope they add some single battle\n"
	.string "teams soon, though.$"

BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor2_Text_0:
# 381 "data/scripts/simple_npcs.pory"
	.string "The sample sets shop is really useful if\n"
	.string "you want to try some new POKéMON, but\l"
	.string "aren't sure how to train them.$"

BattleFrontier_Underground_B1F_EventScript_SampleShop_Visitor2_Text_1:
# 382 "data/scripts/simple_npcs.pory"
	.string "It's a great way to save time when\n"
	.string "experimenting or building a new team!$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_0:
# 393 "data/scripts/simple_npcs.pory"
	.string "If you want to try a new style of\n"
	.string "battling, maybe look at changing the\l"
	.string "battle ban lists - or even trying a new\l"
	.string "ruleset!$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_1:
# 394 "data/scripts/simple_npcs.pory"
	.string "You can even play against the old\n"
	.string "battle frontier sets if you'd like, too.$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_2:
# 395 "data/scripts/simple_npcs.pory"
	.string "The possibilities are endless!$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_0:
# 404 "data/scripts/simple_npcs.pory"
	.string "How do you feel about dynamax battles?$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_1:
# 405 "data/scripts/simple_npcs.pory"
	.string "Some people prefer them over normal\n"
	.string "battles.$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_2:
# 406 "data/scripts/simple_npcs.pory"
	.string "Me? I just like the cool Gigantamax\n"
	.string "formes!$"

BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_0:
# 417 "data/scripts/simple_npcs.pory"
	.string "Have you ever played in a tournament\n"
	.string "before?$"

BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_1:
# 418 "data/scripts/simple_npcs.pory"
	.string "I've heard they hold them in a place far\n"
	.string "away from here.$"

BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_2:
# 419 "data/scripts/simple_npcs.pory"
	.string "You can even qualify for the world\n"
	.string "championships!$"

BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor2_Text_0:
# 428 "data/scripts/simple_npcs.pory"
	.string "I've won lots of games at the Battle\n"
	.string "Frontier, but I'm not sure I'm ready for\l"
	.string "union room battles just yet ...$"

BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor2_Text_1:
# 429 "data/scripts/simple_npcs.pory"
	.string "I guess the only way to find out is to\n"
	.string "try!$"
